apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: prior-kiwi-python 
  janus-idp.io/tekton: prior-kiwi-python
  backstage.io/kubernetes-id: prior-kiwi-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: prior-kiwi-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  